### ISSUE TITLE
Power/Solutions Efficiency

### ISSUE THREAD

**Issue by riweston** [beararmy/EWBF-GPU-Tweak-benchmarker#2]
You should add some code to measure the efficiency watts/solutions

https://github.com/beararmy/EWBF-GPU-Tweak-benchmarker/blob/9eb01b4ee3ef04fb506cbcc7e8775d7bc2cbd91b/benchmarker.ps1#L93

**Comment by beararmy** [comment]
Good point, that value is actually already returned by the EWBF API. Cheaper to pull another variable than to do the maths afterwards.
